### ISSUE TITLE
Getting Attribute Errors: 'list' object has no attribute 'search'

### ISSUE THREAD

**Issue by ufaroooq** [johnomics/tapestry#11]
Hello. 
I am trying to run `Tapestry-v1.0.1` with with following command

```
weave --assembly NP01_pilonX3.fasta --reads NP01_chopper.fastq.gz --telomere TTAGGG --length 10000 --mincontigalignment 1000 --output ./tapestry_analysis/NP01 --cores 90 --forcereadoutput
```

The reads subsampling and alignment parts run without any error but afterwars it throws Bioconda warnings and the a python error.

### Bioconda Warning:
```
Processing contigs:   0%|          | 0/93 [00:00<?, ? contig/s]/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/Bio/motifs/__init__.py:481: BiopythonDeprecationWarning: The instances attribute has been deprecated. Instead of mymotif.instances, please use mymotif.alignment.sequences.
  warnings.warn(
/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/Bio/motifs/__init__.py:481: BiopythonDeprecationWarning: The instances attribute has been deprecated. Instead of mymotif.instances, please use mymotif.alignment.sequences.
```

### Python Error:

```
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
                    ^^^^^^^^^^^^^^^^^^^
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tapestry/contig.py", line 40, in process_contig
    contig.process()
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tapestry/contig.py", line 120, in process
    self.tel_start, self.tel_end = self.num_telomeres()
                                   ^^^^^^^^^^^^^^^^^^^^
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tapestry/contig.py", line 172, in num_telomeres
    start_matches += len(list(s.instances.search(self.rec[:1000].seq)))
                              ^^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'search'
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/bin/weave", line 45, in <module>
    assembly = Assembly(args.assembly, args.reads, args.telomere, args.output, args.cores, args.depth, args.length, args.windowsize, args.forcereadoutput, args.mincontigalignment)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tapestry/assembly.py", line 109, in __init__
    self.process_contigs()
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tapestry/assembly.py", line 316, in process_contigs
    for contig in tapestry_tqdm(p.imap(process_contig, self.contigs.values()), total=len(self.contigs), desc="Processing contigs"):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/site-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/vast/ti78qem/tools/miniconda3/envs/tapestry/lib/python3.12/multiprocessing/pool.py", line 873, in next
    raise value
AttributeError: 'list' object has no attribute 'search'

```

### Here is the complete LOG file attached

[NP01_tapestry.log](https://github.com/user-attachments/files/18200101/NP01_tapestry.log)

Can you guide me in resolving this issue.
Thank you.

**Comment by Changwanseo** [comment]
conda install biopython=1.81

**Comment by ufaroooq** [comment]
@Changwanseo Thank you. works perfectly.

**Comment by ufaroooq** [comment]
Thank you. Works perfectly. @Changwanseo
